services:
  postgres:
    image: postgres:19beta1-trixie
    environment:
      POSTGRES_DB: tabla
      POSTGRES_USER: tabla
      POSTGRES_PASSWORD: tabla
    ports:
      - "5432"
    volumes:
      - tabla-postgres-data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U tabla -d tabla" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  tabla-postgres-data: