[project]
name = "python-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "availe", email = "94802525+availe@users.noreply.github.com" }
]
requires-python = ">=3.14.7"
dependencies = []

[project.scripts]
python-service = "python_service:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
